don't error when tripwire finds a problem

diff --git a/jobs/tripwire/templates/bin/run-report.sh.erb b/jobs/tripwire/templates/bin/run-report.sh.erb
--- a/jobs/tripwire/templates/bin/run-report.sh.erb
+++ b/jobs/tripwire/templates/bin/run-report.sh.erb
@@ -19,7 +19,11 @@ if [[ ! -f $LOCAL_KEY_PATH || ! -f $SITE_KEY_PATH ]]; then
   $PACKAGE_DIR/sbin/tripwire -m i ${TW_LOCATIONS} -P <%= p('tripwire.localpass') %>
 fi
 
+# tripwire exits nonzero when it finds a modification, so we don't want to exit here
+set +e
 $PACKAGE_DIR/sbin/tripwire -m c $TW_LOCATIONS -P <%= p('tripwire.localpass') %> > report.txt
+set -e
+
 logger -t tripwire.report -f report.txt
 
 /var/vcap/jobs/tripwire/bin/aggregate-report.py report.txt /var/vcap/jobs/node_exporter/config/tripwire.prom
